### PR TITLE
Add/update images (via #25, #37)

### LINKED ISSUE #26: Official portrait for Amata Coleman Radewagen - R000600
amata official portrait

Bioguide: R000600
Name: Amata Coleman Radewagen
This image was received after contacting the office. Below is the correspondence with the office:

---

Please see attachment.

Jared Michael P. Christel
Legislative Correspondent
Congresswoman Aumua Amata C. Radewagen
American Samoa At Large District (AQ00)
1339 Longworth HOB
T: (202) 225-8577
F: (202)225-8757

-----Original Message-----
From: webforms@hhws-www2.house.gov [mailto:webforms@hhws-www2.house.gov]
Sent: Monday, March 30, 2015 5:05 PM
To: WebForms, RadewagenAQ
Subject: Website Problem

 WEB PAGE WITH PROBLEM: https://radewagen.house.gov

 NATURE OF PROBLEM:
 I can't find Rep. Radewagen's official House portrait. I'm looking to add the government made, copyright free image to a repository of images of members of Congress that others can freely use. Please let me know where I can find this.

 Thank you!

### LINKED ISSUE #27: Official portrait for David Perdue - P000612
davidperdueofficialheadshot2015

Bioguide: P000612
Name: David Perdue
Image from his Senate website here:
http://www.perdue.senate.gov/sites/default/files/DavidPerdueOfficialHeadshot2015.jpg

### LINKED ISSUE #28: Official portrait for Joni Ernst - E000295
sen joni ernst - official portrait

Bioguide: E000295
Name: Joni Ernst
Image from her Senate website here:
http://www.ernst.senate.gov/sites/default/files/Sen.%20Joni%20Ernst%20-%20Official%20Portrait.jpg

### LINKED ISSUE #29: Official portrait for Mike Rounds - R000605
official portrait

Bioguide: R000605
Name: Mike Rounds
Image provided by his press secretary, Katie Douglas, after emailing a request for the government-made, copyright-free image.

### LINKED ISSUE #30: Official portrait for Daniel Sullivan - S001198
dssullivan official portrait

Bioguide: S001198
Name: Daniel Sullivan
Image provided by his press secretary, Mike Anderson, after emailing a request for the government-made, copyright-free image.

### LINKED ISSUE #36: Official portrait for Cresent Hardy - H001070
88cea7de-ed95-44e1-9983-958eec980686

Bioguide: H001070
Name: Cresent Hardy
Image from his House website here:
http://hardyforms.house.gov/uploadedphotos/highresolution/88cea7de-ed95-44e1-9983-958eec980686.jpg

### LINKED ISSUE #38: Official portrait for Bruce Westerman - W000821
westerman_official

Bioguide: W000821
Name: Bruce Westerman
Image from his House website here:
https://westerman.house.gov/media-center/photo-galleries/official-photo-rep-bruce-westerman

### LINKED ISSUE #40: Official portrait for Rick Allen - A000372
allen-headshot

Bioguide: A000372
Name: Rick Allen
Source link: http://allen.house.gov/uploadedphotos/highresolution/949c137d-ff13-4c33-8a92-11a4f17263a6.jpg

Metadata
name: Official House Website for Rick Allen
link: http://allen.house.gov/

### LINKED ISSUE #41: Official portrait for Donald Beyer - B001292
beyer-headshot

Bioguide: B001292
Name: Donald Beyer
Full source link: https://beyer.house.gov/uploadedphotos/highresolution/353eed9b-2899-47a6-b1c0-5efdfbdee33b.jpg

Metadata
name: Official House Website for Donald Beyer
link: https://beyer.house.gov/about/presskit.htm

### LINKED ISSUE #42: Official portrait for Ken Buck - B001297
buck-headshot

Bioguide: B001297
Name: Ken Buck
Full source link: https://buck.house.gov/sites/buck.house.gov/files/wysiwyg_uploaded/2014-11-14_knb_0128.jpg

Metadata
name: Official House Website for Ken Buck
link: https://buck.house.gov/official-photo

### LINKED ISSUE #43: Official portrait for Barbara Comstock - C001105
2015-02-18_ec_0019

Bioguide: C001105
Name: Barbara Comstock
Full source link: https://comstock.house.gov/sites/comstock.house.gov/files/2015-02-18_ec_0019.jpg

Metadata
name: Official House Website for Barbara Comstock
link: https://comstock.house.gov/about/full-biography

### LINKED ISSUE #44: Official portrait for Ryan Costello - C001106
pa06-costello-officialphoto

Bioguide: C001106
Name: Ryan Costello
Full source link: https://costello.house.gov/sites/costello.house.gov/files/styles/congress_image_medium/public/wysiwyg_uploaded/PA06-Costello-officialphoto.jpg?itok=egcbIqY9

Metadata
name: Official House Website for Ryan Costello
link: https://costello.house.gov/about

### LINKED ISSUE #45: Official portrait for Tom Emmer - E000294
offical photo_emmer
Bioguide: E000294
Name: Tom Emmer
Full source link: https://emmer.house.gov/sites/emmer.house.gov/files/wysiwyg_uploaded/Offical%20Photo_0.jpg

Metadata
name: Official House Website for Tom Emmer
link: https://emmer.house.gov/about

### LINKED ISSUE #46: Official portrait for Gwen Graham - G000575
graham headshot

Bioguide: G000575
Name: Gwen Graham
Full source link: https://graham.house.gov/sites/graham.house.gov/files/featured_image/Graham%20Headshot.jpg

Metadata
name: Official House Website for Gwen Graham
link: https://graham.house.gov/about/full-biography

### LINKED ISSUE #47: Official portrait for Donald Norcross - N000188
repdonaldnorcross-official

Bioguide: N000188
Name: Donald Norcross
Full source link: https://norcross.house.gov/sites/norcross.house.gov/files/RepDonaldNorcross-official.jpg

Metadata
name: Official House Website for Donald Norcross
link: http://norcross.house.gov/about/full-biography

### LINKED ISSUE #48: Official portrait for Norma Torres - T000474
official photo-torres

Bioguide: T000474
Name: Norma Torres
Full source link: https://torres.house.gov/sites/torres.house.gov/files/Official%20Photo.jpg

Metadata
name: Official House Website for Norma Torres
link: https://torres.house.gov/about/full-biography

### LINKED ISSUE #49: Official portrait for Dave Trott - T000475
rep trott_officialphoto

Bioguide: T000475
Name: Dave Trott
Full source link: https://trott.house.gov/sites/trott.house.gov/files/documents/Rep.Trott_OfficialPhoto.jpg

Metadata
name: Official House Website for Dave Trott
link: https://trott.house.gov/about/full-biography

### LINKED ISSUE #50: Official portrait for Pete Aguilar - A000371
headshot_0

Bioguide: A000371
Name: Pete Aguilar
Full source link: https://aguilar.house.gov/sites/aguilar.house.gov/files/styles/congress_image_medium/public/wysiwyg_uploaded/Headshot_0.jpg

Metadata
name: Official House Website for Pete Aguilar
link: https://aguilar.house.gov/about/full-biography

### LINKED ISSUE #51: Official portrait for Mark DeSaulnier - D000623
md portrait

Bioguide: D000623
Name: Mark DeSaulnier
Full source link: https://desaulnier.house.gov/sites/desaulnier.house.gov/files/styles/congress_image_medium/public/wysiwyg_uploaded/MD%20Portrait.jpg

Metadata
name: Official House Website for Mark DeSaulnier
link: https://desaulnier.house.gov/about

### LINKED ISSUE #52: Official portrait for Cory A. Booker - B001288
booker headshot
Bioguide: B001288
Name: Cory A. Booker

Metadata
name: Photo provided by Booker's Senate office over email. Copyright-free status confirmed in email with Director of Scheduling Unjin Lee and Chief of Staff Matt Klapper.
link: Not available

### LINKED ISSUE #53: Official portrait for David Young - Y000066
dey headshot

Bioguide: Y000066
Name: David Young
Full source link: https://davidyoung.house.gov/sites/davidyoung.house.gov/files/documents/DEY%20Headshot.jpg

Metadata
name: Official House Website for David Young
link: https://davidyoung.house.gov/about/full-biography

### LINKED ISSUE #56: Official portrait for Elise Stefanik - S001196
official portrait

Bioguide: S001196
Name: Elise Stefanik
Full source link: https://stefanik.house.gov/sites/stefanik.house.gov/files/documents/Official%20Portrait.jpg

Metadata
name: Official House Website for Elise Stefanik
link: https://stefanik.house.gov/about/full-biography

### LINKED ISSUE #59: Official portrait for Rod Blum - B001294
congressman blum headshot

Bioguide: B001294
Name: Rod Blum

Metadata
name: Photo provided by Rep. Rod Blum's House office over email. Copyright-free status confirmed by a member of his staff.
link: Not available

### LINKED ISSUE #60: Official portrait for Will Hurd - H001073
official

Bioguide: H001073
Name: Will Hurd
Full source link: http://hurd.house.gov/sites/hurd.house.gov/files/official.jpg

Metadata
name: Official House Website for Will Hurd
link: https://hurd.house.gov/about/full-biography

### LINKED ISSUE #61: Official portrait for Steve Knight - K000387
headshot

Bioguide: K000387
Name: Steve Knight

Metadata
name: Photo provided by Rep. Steve Knight's House office over email. Copyright-free status confirmed by a member of his staff.
link: Not available

### LINKED ISSUE #62: Official portrait for John Ratcliffe - R000601
jlr_official_photo_cropped

Bioguide: R000601
Name: John Ratcliffe

Metadata
name: High resolution photo provided by Rep. John Ratcliffe's House office over email. Copyright-free status confirmed by a member of his staff.
link: https://ratcliffe.house.gov/press-kit

### LINKED ISSUE #63: Official portrait for Barry Loudermilk - L000583
official barry_loudermilk

Bioguide: L000583
Name: Barry Loudermilk

Metadata
name: Photo provided by Rep. Barry Loudermilk's House office over email. Copyright-free status confirmed by a member of his staff.
link: Not available

### LINKED ISSUE #64: Official portrait for Buddy Carter - C001103
official photo

Bioguide: C001103
Name: Buddy Carter

Metadata
name: Photo provided by Rep. Buddy Carter's House office over email. Copyright-free status confirmed by a member of his staff.
link: Not available

### LINKED ISSUE #65: Official portrait for Brian Babin - B001291
official headshot
Bioguide: B001291
Name: Brian Babin

Metadata
name: Photo provided by Rep. Brian Babin's House office over email. Copyright-free status confirmed by a member of his staff.
link: Not available

### LINKED ISSUE #67: Official portrait for Bradley Mark Walker - W000819
mwalker_officialphoto
Bioguide: W000819
Name: Bradley Mark Walker

Metadata
name: Photo provided by Rep. Walker's House office over email. Copyright-free status confirmed by a member of his staff.
link: Not available

### LINKED ISSUE #68: Official portrait for Steve Russell - R000604
congressman steve russell official photo

Bioguide: R000604
Name: Steve Russell

Metadata
name: Photo provided by Rep. Russell's House office over email. Copyright-free status confirmed by a member of his staff.
link: Not available

### LINKED ISSUE #69: Official portrait for Mike Bost - B001295
bost official headshot

Bioguide: B001295
Name: Mike Bost

Metadata
name: Photo provided by Rep. Bost's House office over email. Copyright-free status confirmed by a member of his staff.
link: Not available

### LINKED ISSUE #70: Official portrait for Brendan Boyle - B001296
2015-04-21_ec_0029

Bioguide: B001296
Name: Brendan Boyle

Metadata
name: Photo provided by Rep. Boyle's House office over email. Copyright-free status confirmed by a member of his staff.
link: Not available

### LINKED ISSUE #71: Official portrait for Tom MacArthur - M001193
macarthur headshot

Bioguide: M001193
Name: Tom MacArthur

Metadata
name: Photo provided by Rep. MacArthur's House office over email. Copyright-free status confirmed by a member of his staff.
link: Not available

### LINKED ISSUE #72: Official portrait for Ruben Gallego - G000574
gallego

Bioguide: G000574
Name: Ruben Gallego

Metadata
name: Photo provided by Rep. Gallego's House office over email. Copyright-free status confirmed by a member of his staff.
link: Not available

### LINKED ISSUE #74: Official portrait for John Katko - K000386
katko2

Bioguide: K000386
Name: John Katko

Metadata
name: Photo provided by Rep. Katko's House office over email. Copyright-free status confirmed by a member of his staff.
link: Not available

### LINKED ISSUE #75: Official portrait for Martha McSally - M001197
mcsally portrait_cropped copy

Bioguide: M001197
Name: Martha McSally

Metadata
name: Photo provided by Rep. McSally's House office over email. Copyright-free status confirmed by a member of his staff.
link: Not available

### LINKED ISSUE #76: Official portrait for Glenn Grothman - G000576
2015 gg official portrait_final

Bioguide: G000576
Name: Glenn Grothman

Metadata
name: Photo provided by Rep. Grothman's House office over email. Copyright-free status confirmed by a member of his staff.
link: Not available

### LINKED ISSUE #77: Official portrait for Carlos Curbelo - C001107
officialpic

Bioguide: C001107
Name: Carlos Curbelo

Metadata
name: Photo provided by Rep. Curbelo's House office over email. Copyright-free status confirmed by a member of his staff.
link: Not available

### LINKED ISSUE #78: Official portrait for Garret Graves - G000577
rep garret graves

Bioguide: G000577
Name: Garret Graves

Metadata
name: Photo provided by Rep. Graves House office over email. Copyright-free status confirmed by a member of his staff.
link: Not available

### LINKED ISSUE #79: Official portrait for Dan Newhouse - N000189
rep dan newhouse

Bioguide: N000189
Name: Dan Newhouse

Metadata
name: Photo provided by Rep. Newhouse's House office over email. Copyright-free status confirmed by a member of his staff.
link: Not available

### LINKED ISSUE #80: Official portrait for Gary Palmer - P000609
palmer official photo

Bioguide: P000609
Name: Gary Palmer

Metadata
name: Photo provided by Rep. Palmer's House office over email. Copyright-free status confirmed by a member of his staff.
link: Not available

### LINKED ISSUE #81: Official portrait for Bonnie Watson Coleman - W000822
bwc headshot

Bioguide: W000822
Name: Bonnie Watson Coleman

Metadata
name: Photo provided by Rep. Watson Coleman's House office over email. Copyright-free status confirmed by a member of his staff.
link: Not available

### LINKED ISSUE #82: Official portrait for Bruce Poliquin - P000611
poliquin official portrait

Bioguide: P000611
Name: Bruce Poliquin

Metadata
name: Photo provided by Rep. Poliquin's House office over email. Copyright-free status confirmed by a member of his staff.
link: Not available

### LINKED ISSUE #83: Official portrait for Ryan Zinke - Z000018
headshot

Bioguide: Z000018
Name: Ryan Zinke

Metadata
name: Photo provided by Rep. Zinke's House office over email. Copyright-free status confirmed by a member of his staff.
link: Not available

### LINKED ISSUE #84: Official portrait for David Rouzer - R000603
dcr headshot

Bioguide: R000603
Name: David Rouzer

Metadata
name: Photo provided by Rep. Rouzer's House office over email. Copyright-free status confirmed by a member of his staff.
link: Not available

### LINKED ISSUE #85: Official portrait for Thom Tillis - T000476
offical headshot
Bioguide: T000476
Name: Thom Tillis

Metadata
name: Photo provided by the Senate office of Thom Tillis over email. Copyright-free status confirmed by a member of his staff.
link: Not available

### LINKED ISSUE #86: Official portrait for Ben Sasse - S001197
sasse official portrait

Bioguide: S001197
Name: Ben Sasse

Metadata
name: Photo provided by Sen. Ben Sasse's Senate office over email. Copyright-free status confirmed by a member of his staff. It's the full resolution version of the image seen on his Senate website's "About Ben" page.
link: http://www.sasse.senate.gov/content/about-ben

### LINKED ISSUE #87: Official portrait for Alma Adams - A000370
official photo

Bioguide: A000370
Name: Alma Adams

Metadata
name: Photo provided by the House office of Rep. Alma Adams over email. Copyright-free status confirmed by a member of her staff.
link: Not available

### LINKED ISSUE #88: Official portrait for Jody Hice - H001071
headshot1twitter

Bioguide: H001071
Name: Jody Hice

Metadata
name: Photo provided by Rep. Hice's House office over email. Copyright-free status confirmed by a member of his staff.
link: Not available

### LINKED ISSUE #89: Official portrait for Ralph Abraham - A000374
abraham hi res

Bioguide: A000374
Name: Ralph Abraham

Metadata
name: Photo provided by the House office of Rep. Abraham over email. Copyright-free status confirmed by a member of his staff.
link: Not available

### LINKED ISSUE #90: Official portrait for French Hill - H001072
french_hill_official_photo

Bioguide: H001072
Name: French Hill

Metadata
name: Photo provided by the House office of Rep. Hill over email. Copyright-free status confirmed by a member of his staff.
link: Not available

### LINKED ISSUE #91: Official portrait for Debbie Dingell - D000624
d2 headshot

Bioguide: D000624
Name: Debbie Dingell

Metadata
name: Photo provided by the House office of Rep. Debbie Dingell over email. Copyright-free status confirmed by a member of her staff.
link: Not available

### LINKED ISSUE #92: Official portrait for Alex Mooney - M001195
2015-02-02_pnn_0002

Bioguide: M001195
Name: Alex Mooney

Metadata
name: Photo provided by the House office of Rep. Mooney over email. Copyright-free status confirmed by a member of his staff.
link: Not available

### LINKED ISSUE #94: Official portrait for Ted Lieu - L000582
replieu_headshot

Bioguide: L000582
Name: Ted Lieu

Metadata
name: Photo provided by the House office of Rep. Lieu over email. Copyright-free status confirmed by a member of his staff.
link: Not available

### LINKED ISSUE #95: Official portrait for Mimi Walters - W000820
updated headshot

Bioguide: W000820
Name: Mimi Walters

Metadata
name: Photo provided by the House office of Rep. Walters over email. Copyright-free status confirmed by a member of her staff.
link: Not available

### LINKED ISSUE #96: Official portrait for Stacey Plaskett - P000610
official member port

Bioguide: P000610
Name: Stacey Plaskett

Metadata
name: Photo provided by the House office of Rep. Plaskett over email. Copyright-free status confirmed by a member of her staff.
link: Not available

### LINKED ISSUE #97: Official portrait for Seth Moulton - M001196
ma06_headshot

Bioguide: M001196
Name: Seth Moulton

Metadata
name: Photo provided by the House office of Rep. Moulton over email. Copyright-free status confirmed by a member of his staff.
link: Not available

### LINKED ISSUE #98: Official portrait for Brenda Lawrence - L000581
2015-02-23_lawrence_0012

Bioguide: L000581
Name: Brenda Lawrence

Metadata
name: Photo provided by the House office of Rep. Lawrence over email. Copyright-free status confirmed by a member of her staff.
link: Not available

### PR DESCRIPTION
**Pull request by hugovk**
See commits for details of additions/updates.

Also metadata for E000295 R000605 S001198 W000821 R000600 P000612.

The [visual diff](https://github.com/unitedstates/images/pull/39/files) of the original vs. the new is good!

Closes #26
Closes #27
Closes #28
Closes #29
Closes #30
Closes #36
Closes #38
Closes #40
Closes #41
Closes #42
Closes #43
Closes #44
Closes #45
Closes #46
Closes #47
Closes #48
Closes #49
Closes #50
Closes #51
Closes #52
Closes #53
Closes #56
Closes #59
Closes #60
Closes #61
Closes #62
Closes #63
Closes #64
Closes #65
Closes #67
Closes #68
Closes #69
Closes #70
Closes #71
Closes #72
Closes #74
Closes #75
Closes #76
Closes #77
Closes #78
Closes #79
Closes #80
Closes #81
Closes #82
Closes #83
Closes #84
Closes #85
Closes #86
Closes #87
Closes #88
Closes #89
Closes #90
Closes #91
Closes #92
Closes #94
Closes #95
Closes #96
Closes #97
Closes #98

### CODE REVIEW

**Comment by hugovk** [comment]
@konklone @JoshData Feel free to merge this whenever you're ready (assuming the new images are acceptable), so then the new images can go live right away. We don't need to wait until all the updates are ready (it could be some take a long time to respond to email). I'll make new PRs for new images as they come in.

**Comment by nickom** [comment]
:+1: 
Thanks so much for all your help @hugovk! Very satisfying to see [the visual diff improvements](https://github.com/unitedstates/images/pull/39/files)!

**Comment by JoshData** [comment]
I can't use this with the metadata files all kind of a mess. (The `name`s aren't consistently formatted and `link: Not available` would make links on GovTrack look like I don't know what a URL is.)

**Comment by hugovk** [comment]
@JoshData: I'll remove the `link: Not available` lines. What format do you suggest for the `name:`s?

**Comment by JoshData** [comment]
I use something very simple in this format:

> Office of Donald Beyer

and a link to the representative's website. (A missing `link` field isn't going to help me either...)

**Comment by nickom** [comment]
Josh, I would encourage you to review the work we've been doing on this repo more closely. Linking to the member's websites would be incorrect because the images don't exist on their office websites (or anywhere online in most cases). I've had to contact each office individually to track down these copyright-free files.

If you have specific concerns about your own needs for GovTrack, I'd suggest making them downstream instead of making the central repo have misleading metadata. Or perhaps just drop the link field

**Comment by JoshData** [comment]
> would be incorrect

That depends entirely on what the field is supposed to hold. I was the one that requested it (in #6), so that I could use this repo's data in GovTrack, but we didn't define what the field was supposed to contain.

I'm not changing GovTrack. :) You guys are welcome to commit here whatever's helpful for you all and I'll just keep maintaining my own photo database like I've done forevers.

**Comment by hugovk** [comment]
OK, so what is the metadata for? #6 says it's to show credit/source information for each image, in case images are included from other sources than the GPO member guide, which is the case.

For a GPO image we've used:

``` yaml
name: GPO Member Guide
link: http://memberguide.gpo.gov
```

For a non-GPO image, I think something like this could also be seen as valid:

``` yaml
name: Office of Donald Beyer
link: https://beyer.house.gov
```

The image did come from his office, and here's a link to the office.

**Comment by JoshData** [comment]
Exactly. Here's how I use it (the red box at the bottom):

image

So I'm just looking for a short noun and a link to whatever the noun refers to.

**Comment by hugovk** [comment]
I've just committed https://github.com/hugovk/images/commit/0a66b8fd7734a1123738e8fabf7cd6384a5e12e7 to this PR which shortens the `name:` values.

Thirty-eight `link:` values would need updating manually:

```
A000370.yaml:link: Not available
A000374.yaml:link: Not available
B001288.yaml:link: Not available
B001291.yaml:link: Not available
B001294.yaml:link: Not available
B001295.yaml:link: Not available
B001296.yaml:link: Not available
C001103.yaml:link: Not available
C001107.yaml:link: Not available
D000624.yaml:link: Not available
G000574.yaml:link: Not available
G000576.yaml:link: Not available
G000577.yaml:link: Not available
H001071.yaml:link: Not available
H001072.yaml:link: Not available
K000386.yaml:link: Not available
K000387.yaml:link: Not available
L000581.yaml:link: Not available
L000582.yaml:link: Not available
L000583.yaml:link: Not available
M001193.yaml:link: Not available
M001195.yaml:link: Not available
M001196.yaml:link: Not available
M001197.yaml:link: Not available
N000189.yaml:link: Not available
P000609.yaml:link: Not available
P000610.yaml:link: Not available
P000611.yaml:link: Not available
R000600.yaml:link: Not available
R000603.yaml:link: Not available
R000604.yaml:link: Not available
R000605.yaml:link: Not available
S001198.yaml:link: Not available
T000476.yaml:link: Not available
W000819.yaml:link: Not available
W000820.yaml:link: Not available
W000822.yaml:link: Not available
Z000018.yaml:link: Not available
```

**Comment by hugovk** [comment]
If anyone wants to update some of the `link:`s in this PR, probably the easiest way is to edit the files on [my branch](https://github.com/hugovk/images/tree/gh-pages/congress/metadata), click the pen icon to edit, then save/submit them as new PRs to my branch. They'll then automatically be added to this PR.

**Comment by nickom** [comment]
What do y'all think of finishing up and merging this pull request? I don't expect the two remaining members from Issue #37 to be resolved any time soon and we shouldn't hold back on letting projects that use /unitedstates have access to the higher quality images.

In terms of the remaining offices, Rep. Rice hasn't had her official portrait taken and I've emailed/called everyone I can find in Rep. Moolenaar's office for a high resolution portrait and they haven't sent me anything.

**Comment by hugovk** [comment]
@konklone OK to merge?

**Comment by konklone** [comment]
:+1: Sorry, didn't realize I was being waited on!

**Pull request merged**
