### PR TITLE
Images for 60 new Congress Members

### PR DESCRIPTION
**Pull request by plantfansam**
So these are sourced from the [GPO New Member Pictorial Directory](http://www.gpo.gov/fdsys/browse/collection.action?collectionCode=GPO&browsePath=Congressional+Pictorial+Directory%2F114th+Congress&searchPath=Congressional+Pictorial+Directory%2F114th+Congress&leafLevelBrowse=false&isCollapsed=false&isOpen=true&ancestors=root&packageid=GPO-PICTDIR-NEW-114&ycord=42) (thanks to @JoshData for extracting these images from the pdf). I manually matched up the new members with their bioguide ids and reviewed them once, but a spot check would probably be prudent, unless that was part of @hugovk's [review](https://github.com/unitedstates/images/issues/20#issuecomment-69004139).

`missing.py` shows that we're still missing [eight legislators](https://gist.github.com/handlers/d63d29de81711debc504). Haven't yet looked into why they're missing.

This references issue #20.

### CODE REVIEW

**Comment by hugovk** [comment]
My quick check was just a technical check -- the files are in the correct locations, look the right size, the metadata looks fine, are only new files. So :+1: from that point of view!

If someone else wants to do a couple of spot check for correct images, go ahead.

By the way, Travis CI also runs `missing.py` so you can see who's missing from the logs ([e.g.](https://travis-ci.org/unitedstates/images/jobs/46200684#L312)).

**Comment by JoshData** [comment]
Go ahead and merge. I'll probably review it again before importing into GovTrack, but unfortunately I won't get to that for a while.

**Comment by plantfansam** [comment]
OK, thanks for the clarification/help, all! I'm good with a merge, then! (I can't merge myself because I don't have write access to the repo).

**Comment by hugovk** [comment]
Merged, thanks!

Closes #20.

**Comment by JoshData** [comment]
Finally got these pulled into GovTrack. Just wanted to say thanks to @handlers and @hugovk!

**Comment by plantfansam** [comment]
No problem, @JoshData, and thanks for _your_ help (and @hugovk's)!

**Pull request merged**
