### PR TITLE
simplify the scraper by using Congress.gov to map bioguide IDs to GPO image URLs

### PR DESCRIPTION
**Pull request by JoshData**
The GPO member guide scraper has to resolve names to bioguide IDs. This is hard to verify the accuracy of.

Congress.gov has thumbnail images of Members, and they happen to store the photo file using the same name as on memberguide.gpo.gov. So we can use Congress.gov as the cross-walk between bioguide IDs and memberguide URLs to full-size photos.

This PR revises the scraper to fetch new images by scanning Congress.gov first, and then getting the full size image file directly from memberguide.gpo.gov.

I've also added separate commits to this that fetches all images available for the 114th Congress & updates the resized copies.

Think this is a good approach?

### CODE REVIEW

**Comment by hugovk** [comment]
Yes, I think this approach is good. It removes a load of code that was used in resolving the bioguide IDs.

The removed code is the tested code, so we don't have any valid tests anymore, and so they all fail. The remaining code doesn't have so much testable logic as before, so it probably doesn't matter so much having it unit tested.

If we don't need unit tests, I propose we still use the CI, as it is doing some other useful tasks: enumerates any missing images, does some static analysis.

I can clear up the test stuff if you like, but these lines can be removed:
https://github.com/unitedstates/images/blob/gh-pages/.travis.yml#L25
https://github.com/unitedstates/images/blob/gh-pages/.travis.yml#L28
https://github.com/unitedstates/images/blob/gh-pages/.travis.yml#L32-L33
https://github.com/unitedstates/images/blob/gh-pages/requirements.txt#L1

This dir:
https://github.com/unitedstates/images/tree/gh-pages/test

This file:
https://github.com/unitedstates/images/blob/gh-pages/.coveragerc

**Comment by hugovk** [comment]
(Alternatively, I have a couple of uncommitted tests that don't do a huge amount, but would at ensure the code is importable and runnable to some degree on each Python version.)

``` python
+    def test_save_metadata(self):
+        """ Test file is saved """
+        bioguide_id = "A000000"
+        gpo_member_photos.save_metadata(bioguide_id)
+        self.assertTrue(os.path.exists("congress/metadata/A000000.yaml"))
+
+    def test_resize_photos(self):
+        """ Test callable """
+        gpo_member_photos.resize_photos()
```

**Comment by hugovk** [comment]
Oh, one more thing: scripts/missing.py was basically running two functions from the old scraper. If there's still value in having it (it checks against the "master" legislators-current.yaml list), then those two functions should be moved into missing.py.

``` python
if __name__ == "__main__":
    # clone or update legislator YAML
    gpo_member_photos.download_legislator_data()

    legislators = gpo_member_photos.load_yaml(
        "congress-legislators/legislators-current.yaml")
    for l in legislators:
        bioguide = l['id']['bioguide']
        filename = os.path.join("congress", "original", bioguide + ".jpg")
        if file_exists(filename):
            # Only check for yaml if jpg exists
            filename = os.path.join("congress", "metadata", bioguide + ".yaml")
            file_exists(filename)
```

**Comment by JoshData** [comment]
Ok I'll take a look at updating the tests etc. later this week.

Also - good catch on the raise/unlink order. I'll fix that.

**Comment by hugovk** [comment]
Oops, accidentally pushed the `unlink` before `raise` fix to this branch when I thought I was in my own repo, but nevermind.

Anyway, I've created a new PR based on this one, with simplified testing: PR #118.

**Pull request merged**
